print('====== DESAFIO 9 ======')
n = int(input('Digite um número: '))
print('1 x {:2} = {}'.format(n, n*1))
print('2 x {:2} = {}'.format(n, n*2))
print('3 x {:2} = {}'.format(n, n*3))
print('4 x {:2} = {}'.format(n, n*4))
print('5 x {:2} = {}'.format(n, n*5))
print('6 x {:2} = {}'.format(n, n*6))
print('7 x {:2} = {}'.format(n, n*7))
print('8 x {:2} = {}'.format(n, n*8))
print('9 x {:2} = {}'.format(n, n*9))
print('10 x {} = {}'.format(n, n*10))
