print('====== DESAFIO 26 ======')
frase = str(input('Digite uma frase: ')).lower().strip()
print('Número de vezes que aparece a letra A: {}'.format(frase.count('a')))
print('A letra A aparece a primeira vez na posição: {}'.format(frase.find('a')+1))
print('A letra A aparece a última vez na posição: {}'.format(frase.rfind('a')+1))